server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
    - localhost
    labels:
      job: varlogs
      __path__: /var/log/*log

- job_name: journal
  journal:
    json: false
    max_age: 12h
    path: /var/log/journal
  labels:
    job: systemd-journal
  relabel_configs:
    - source_labels: ["__journal__systemd_unit"]
      target_label: "unit"


#Scrape EC2-TESTE

- job_name: ec2-logs
  ec2_sd_configs:
    - region: us-east-2
      access_key: REDACTED
      secret_key: REDACTED
  relabel_configs:
    - source_labels: [__meta_ec2_tag_Name]
      target_label: name
      action: replace
    - source_labels: [__meta_ec2_instance_id]
      target_label: instance
      action: replace
    - source_labels: [__meta_ec2_availability_zone]
      target_label: zone
      action: replace
    - action: replace
      replacement: /var/log/**.log
      target_label: __path__
    - source_labels: [__meta_ec2_private_dns_name]
      regex: "(.*)"
      target_label: __host__


